-- MySQL Script generated by MySQL Workbench
-- Mon Jun 12 11:50:41 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`products` (
  `idproducts` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `proixTTC` INT NOT NULL,
  `weight` INT NULL,
  `remise` INT NULL,
  `image` VARCHAR(200) NULL,
  PRIMARY KEY (`idproducts`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`transporteur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`transporteur` (
  `idtransporteur` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `condition1` INT NOT NULL,
  `condition2` INT NOT NULL,
  `condition3` INT NOT NULL,
  PRIMARY KEY (`idtransporteur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`products_has_transporteur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`products_has_transporteur` (
  `products_idproducts` INT NOT NULL,
  `transporteur_idtransporteur` INT NOT NULL,
  `quantity` INT NULL,
  PRIMARY KEY (`products_idproducts`, `transporteur_idtransporteur`),
  INDEX `fk_products_has_transporteur_transporteur1_idx` (`transporteur_idtransporteur` ASC) ,
  INDEX `fk_products_has_transporteur_products_idx` (`products_idproducts` ASC) ,
  CONSTRAINT `fk_products_has_transporteur_products`
    FOREIGN KEY (`products_idproducts`)
    REFERENCES `mydb`.`products` (`idproducts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_has_transporteur_transporteur1`
    FOREIGN KEY (`transporteur_idtransporteur`)
    REFERENCES `mydb`.`transporteur` (`idtransporteur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
